security:
    providers:
        administrators:
            entity: { class: ArcanaBugtrackerBundle:User, property: username }

    access_control:
        - { path: ^/statuses/*, roles: ROLE_ADMIN }
        - { path: ^/users/*, roles: ROLE_ADMIN }
        - { path: ^/projects/*, roles: ROLE_ADMIN }
        - { path: ^/bugs/add, roles: ROLE_TESTER }
        - { path: ^/bugs/, roles: [ROLE_ADMIN, ROLE_TESTER, ROLE_MANAGER] }
        - { path: ^/bugs/*, roles: [ROLE_TESTER, ROLE_MANAGER] }
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/, roles: [ROLE_ADMIN, ROLE_TESTER, ROLE_MANAGER] }
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        secured_area:
            pattern:   ^/
            anonymous: ~
            form_login: ~
            logout: ~

    encoders:
        Arcana\BugtrackerBundle\Entity\User:
            algorithm: bcrypt
            cost: 12
