root:
    path: /
    defaults:
        _controller: ArcanaBugtrackerBundle:Bugs:list
        path: /bugs
        permanent: true

login:
    path:     /login
    defaults: { _controller: ArcanaBugtrackerBundle:Security:login }
login_check:
    path: /login_check

logout:
    path:   /logout

bugs_list:
    path:     /bugs/
    defaults: { _controller: ArcanaBugtrackerBundle:Bugs:list }
bugs_add:
    path:     /bugs/add
    defaults: { _controller: ArcanaBugtrackerBundle:Bugs:add }
bugs_edit:
    path:     /bugs/{id}
    defaults: { _controller: ArcanaBugtrackerBundle:Bugs:edit }

projects_list:
    path:     /projects/
    defaults: { _controller: ArcanaBugtrackerBundle:Projects:list }
projects_add:
    path:     /projects/add
    defaults: { _controller: ArcanaBugtrackerBundle:Projects:add }
projects_edit:
    path:     /projects/{id}
    defaults: { _controller: ArcanaBugtrackerBundle:Projects:edit }

users_list:
    path:     /users/
    defaults: { _controller: ArcanaBugtrackerBundle:Users:list }
users_add:
    path:     /users/add
    defaults: { _controller: ArcanaBugtrackerBundle:Users:add }
users_edit:
    path:     /users/{id}
    defaults: { _controller: ArcanaBugtrackerBundle:Statuses:edit }

statuses_list:
    path:     /statuses/
    defaults: { _controller: ArcanaBugtrackerBundle:Statuses:list }
statuses_add:
    path:     /statuses/add
    defaults: { _controller: ArcanaBugtrackerBundle:Statuses:add }
statuses_edit:
    path:     /statuses/{id}
    defaults: { _controller: ArcanaBugtrackerBundle:Statuses:edit }



