root:
    path: /
    defaults:
        _controller: ArcanaBugtrackerBundle:Bugs:list
        path: /bugs
        permanent: true

login:
    path:     /login
    defaults: { _controller: ArcanaBugtrackerBundle:Security:login }
login_check:
    path: /login_check

logout:
    path:   /logout

bugs_list:
    path:     /bugs/
    defaults: { _controller: ArcanaBugtrackerBundle:Bugs:list }
bugs_add:
    path:     /bugs/add
    defaults: { _controller: ArcanaBugtrackerBundle:Bugs:add, type: add }
bugs_edit:
    path:     /bugs/{id}
    defaults: { _controller: ArcanaBugtrackerBundle:Bugs:add, type:edit }
    requirements: 
        id: \d+

projects_list:
    path:     /projects/
    defaults: { _controller: ArcanaBugtrackerBundle:Projects:list }
projects_add:
    path:     /projects/add
    defaults: { _controller: ArcanaBugtrackerBundle:Projects:add, type: add }
projects_edit:
    path:     /projects/{id}
    defaults: { _controller: ArcanaBugtrackerBundle:Projects:add, type: edit }
    requirements: 
        id: \d+

users_list:
    path:     /users/
    defaults: { _controller: ArcanaBugtrackerBundle:Users:list }
users_add:
    path:     /users/add
    defaults: { _controller: ArcanaBugtrackerBundle:Users:add, type: add }
users_edit:
    path:     /users/{id}
    defaults: { _controller: ArcanaBugtrackerBundle:Users:add, type: edit }
    requirements: 
        id: \d+

statuses_list:
    path:     /statuses/
    defaults: { _controller: ArcanaBugtrackerBundle:Statuses:list }
statuses_add:
    path:     /statuses/add
    defaults: { _controller: ArcanaBugtrackerBundle:Statuses:add, type: add }
statuses_edit:
    path:     /statuses/{id}
    defaults: { _controller: ArcanaBugtrackerBundle:Statuses:add, type: edit }
    requirements: 
        id: \d+



