parameters:
#    arcana_bugtracker.example.class: Arcana\BugtrackerBundle\Example

services:
#    arcana_bugtracker.example:
#        class: %arcana_bugtracker.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
